export const SITE_CONFIG = {
  icon: 'Fa',
  title: 'Fafa Blog',
  descriptionFafa: 'fafa的个人博客',
  author: 'Simon',
  keywords: ['博客', 'Live2D', 'Animation', 'AE', 'Game'],
  email:'dcfafa0109@gmail.com',
  socialLinks: {
    github: 'https://github.com/LXC-9349/pjfun-blog',
    Telegram: 'https://t.me/pjfun_top',
  },
  foot:{
    github:'https://github.com/LXC-9349/pjfun-blog',
  }
}
//仓库地址
export const GIT_REPO=SITE_CONFIG.socialLinks.github

// Giscus 评论系统配置 https://giscus.app/zh-CN
export const GISCUS_CONFIG = {
  enabled: true, // 启用评论系统
  repo: 'LXC-9349/blog-comment', // GitHub 仓库
  repoId: 'R_kgDOQmj5WA', // 仓库 ID
  category: 'Announcements', // Discussion 分类
  categoryId: 'DIC_kwDOQmj5WM4CzpLf', // 分类 ID
  mapping: 'pathname', // 映射方式
  strict: false, // 严格匹配
  reactionsEnabled: true, // 启用反应
  emitMetadata: false, // 发送元数据
  inputPosition: 'top', // 输入框位置
  lang: 'zh-CN' // 语言
}

// 热门标签
export const HOT_TAGS = [
  'Vue',
  '网页',
  '文本',
  '在线课程',
  '编程教程',
  '职业技能',
  '知识管理',
  '思维导图',
  '学习笔记',
  '教育心得',
  '自我提升'
]

export const I18N_CONFIG = {
  zh: {
    siteTitle: SITE_CONFIG.title,
    siteDescription: '欢迎来到我的个人博客，这里记录了我的技术探索和思考。',
    articleDirectory: '文章目录',
    latestPosts: '最新文章',
    searchPlaceholder: '搜索文章...',
    readMore: '阅读全文',
    excerpt: '这篇文章还没有摘要...',
    noArticles: '暂无文章',
    unknownDate: '未知日期',
    home: '首页',
    toggleTheme: '切换主题',
    search: '搜索',
    close: '关闭',
    loading: '加载中...',
    error: '加载失败',
    success: '操作成功',
    searchHint: '输入关键词搜索...',
    noResults: '未找到相关内容',
    startSearching: '开始搜索...',
    articlesFound: '找到 {count} 篇文章',
    navigation: '导航',
    select: '选择',
    backToTop: '返回顶部',
    backToHome: '返回主页',
    filterByTag: '热门标签',
    clear: '清除',
    noExcerpt: '暂无摘要',
    loadMore: '加载更多',
    noArticlesWithTag: '没有找到标签为「{tag}」的文章',
    // 新增翻译项
    back: '返回',
    print: '打印',
    tags: '标签',
    share: '分享文章',
    readingTime: '分钟阅读',
    copy: '复制',
    download: '下载',
    linkCopied: '链接已复制到剪贴板',
    lightboxImage: '图片预览',
    copyLink: '复制链接',
    adjustFontSize: '调整字体大小',
    showDirectory: '显示目录',
    copyCode: '复制代码',
    fontSizeSmall: '小',
    fontSizeMedium: '中',
    fontSizeLarge: '大',
    // 收藏相关翻译
    addToFavorites: '添加到收藏',
    removeFromFavorites: '从收藏中移除',
    favorite: '收藏',
    favorited: '已收藏',
    // 分享相关翻译
    shareTo: '分享到',
    copied: '已复制',
    wechat: '微信',
    weibo: '微博',
    qq: 'QQ',
    twitter: 'X',
    facebook: '脸书',
    linkedin: '领英',
    telegram: '电报',
    email: '邮件',
    // 收藏相关翻译
    favoritesTitle: '收藏夹',
    yourFavorites: '您的收藏',
    clearAll: '清空所有',
    noFavorites: '暂无收藏',
    noFavoritesDesc: '您还没有收藏任何文章',
    browseArticles: '浏览文章',
    confirmClearAll: '确定要清空所有收藏吗？',
    // 归档相关翻译
    archiveTitle: '文章归档',
    noArchivedArticles: '暂无归档文章',
    totalArticles: '总文章数',
    timeRange: '时间范围',
    // 密码保护相关翻译
    passwordProtected: '密码保护',
    enterPasswordToAccess: '请输入密码以访问此网站',
    password: '密码',
    enterPassword: '请输入访问密码',
    access: '进入网站',
    checking: '验证中...',
    contactForAccess: '请联系网站管理员获取访问权限',
    passwordRequired: '请输入密码',
    incorrectPassword: '密码错误',
    loginError: '登录时发生错误，请稍后重试',
    passwordProtectionNotConfigured: '密码保护未正确配置',
    // 页脚相关翻译
    footerDescription: '一个现代化的个人博客和技术分享平台',
    allRightsReserved: '保留所有权利',
    siteVisitors: '本站访客数',
    siteViews: '本站总访问量',
    pageViews: '当前页面访问量',
    // 阅读进度相关翻译
    continueReading: '继续阅读',
    recentlyViewed: '最近浏览',
    clearRecent: '清除记录',
    noRecentArticles: '暂无最近浏览的文章',
    // 文档查看器相关翻译
    loadingDocument: '正在加载文档...',
    documentLoadError: '文档加载失败',
    retry: '重试',
    documentPreviewNotAvailable: '文档预览不可用',
    documentFormat: '格式: {format}',
    downloadAndViewLocally: '下载并在本地查看',
    document: '文档',
    documentConversionNotSupported:'文档查看失败无法转换',
    // PDF 查看器相关翻译
    prevPage: '上一页 (←)',
    nextPage: '下一页 (→)',
    pageNumber: '页码',
    jumpToPage: '跳转到指定页码',
    jump: '跳转',
    zoomOut: '缩小 (↓)',
    reset: '重置 (0)',
    zoomIn: '放大 (↑)',
    rotate: '旋转 (R)',
    // Excel 查看器相关翻译
    file: '文件',
    insert: '插入',
    formula: '公式',
    openFile: '打开文件',
    pleaseWait: '请稍候...',
    initializingExcelEngine: '正在初始化 Excel 引擎...',
    loadingStyles: '正在加载样式文件...',
    loadingCoreEngine: '正在加载核心引擎...',
    resourceLoadFailed: '资源加载失败，请检查网络或刷新重试',
    newWorkbook: '新建工作簿',
    workbook1: '工作簿1',
    parsingExcelFile: '正在解析 Excel 文件...',
    readFailed: '读取失败',
    checkFileFormat: '请检查文件格式',
    parseFailed: '解析失败',
    ensureValidXlsx: '请确保是有效的 .xlsx 文件',
    loadingExcelFromUrl: '正在从URL加载Excel文件...',
    remoteFile: '远程文件.xlsx',
    loadFailedCheckUrl: '加载失败，请检查URL是否正确',
    // 新增翻译项
    saveAs: '另存为',
    fullscreen: '全屏',
    featureActivated: '功能已激活，请使用上方工具栏进行操作',
    excelEngineNotReady: 'Excel引擎尚未准备好，请稍后再试',
    unableToFindContainer: '无法找到容器元素',
    fullscreenNotSupported: '当前浏览器不支持全屏功能',
    noDataToSave: '没有数据可以保存',
    enterFileName: '请输入文件名',
    saveFailed: '保存失败',
    noDataToPrint: '没有数据可以打印',
    printFailed: '打印失败',
    popupBlocked: '弹窗被阻止，请允许弹窗后重试',
    printPreview: '打印预览',
    info: '提示',
    cancel: '取消',
    confirm: '确认',
    editArticles: '编辑文章',
    edit: '编辑',
    articleEditor: '文章编辑器',
    saving: '保存中...',
    save: '保存',
    files: '文件',
    newFile: '新建文件',
    newFolder: '新建文件夹',
    editorPlaceholder: '在此处输入文章内容...',
    noFileSelected: '未选择文件',
    noFileSelectedDesc: '请选择一个文件开始编辑，或者创建一个新文件',
    gitIntegration: 'Git 集成',
    enterGitToken: '请输入您的 Git 访问令牌以启用文件编辑功能',
    gitProvider: 'Git 服务商',
    accessToken: '访问令牌',
    enterAccessToken: '请输入访问令牌',
    failedToLoadFile: '加载文件失败',
    confirmDelete: '确认删除',
    confirmDeleteFile: '确定要删除文件 "{filename}" 吗？此操作不可撤销。',
    fileDeleted: '文件已删除',
    failedToDeleteFile: '删除文件失败',
    fileCreated: '文件已创建',
    failedToCreateFile: '创建文件失败',
    folderCreated: '文件夹已创建',
    failedToCreateFolder: '创建文件夹失败',
    renamed: '已重命名',
    failedToRename: '重命名失败',
    pleaseEnterToken: '请输入访问令牌',
    tokenSaved: '令牌已保存',
    articleSaved: '文章已保存',
    failedToSaveArticle: '保存文章失败',
    fileName: '文件名',
    folderName: '文件夹名',
    newName: '新名称',
    create: '创建',
    rename: '重命名',
    delete: '删除',
    dataManager:'数据管理',
    noRepoInfo:'未配置仓库',
    chooseEditor:'选择编辑器',
    selectEditorToOpenRepo:'请选择要打开仓库的在线编辑器',
    top:'置顶',
  },
  en: {
    siteTitle: SITE_CONFIG.title,
    siteDescription: 'Welcome to my personal blog where I record my technical explorations and thoughts.',
    articleDirectory: 'Article Directory',
    latestPosts: 'Latest Posts',
    searchPlaceholder: 'Search articles...',
    readMore: 'Read More',
    excerpt: 'This article has no excerpt yet...',
    noArticles: 'No articles available',
    unknownDate: 'Unknown Date',
    home: 'Home',
    toggleTheme: 'Toggle Theme',
    search: 'Search',
    close: 'Close',
    print: 'Print',
    loading: 'Loading...',
    error: 'Failed to load',
    success: 'Operation successful',
    searchHint: 'Type keywords to search...',
    noResults: 'No relevant content found',
    startSearching: 'Start searching...',
    articlesFound: '{count} articles found',
    navigation: 'Navigate',
    select: 'Select',
    backToTop: 'Back to Top',
    backToHome: 'Back to Home',
    noArticlesWithTag: 'No articles found with tag 「{tag}」',
    // 新增翻译项
    back: 'Back',
    tags: 'Tags',
    share: 'Share Article',
    readingTime: 'min read',
    copy: 'Copy',
    download: 'Download',
    linkCopied: 'Link copied to clipboard',
    lightboxImage: 'Image Preview',
    copyLink: 'Copy Link',
    adjustFontSize: 'Adjust Font Size',
    showDirectory: 'Show Directory',
    copyCode: 'Copy Code',
    fontSizeSmall: 'Small',
    fontSizeMedium: 'Medium',
    fontSizeLarge: 'Large',
    // Favorites translations
    addToFavorites: 'Add to Favorites',
    removeFromFavorites: 'Remove from Favorites',
    favorite: 'Favorite',
    favorited: 'Favorited',
    // Sharing translations
    shareTo: 'Share to',
    copied: 'Copied',
    wechat: 'WeChat',
    weibo: 'Weibo',
    qq: 'QQ',
    twitter: 'X',
    facebook: 'Facebook',
    linkedin: 'LinkedIn',
    telegram: 'Telegram',
    email: 'Email',
    // Favorites translations
    favoritesTitle: 'Favorites',
    yourFavorites: 'Your Favorites',
    clearAll: 'Clear All',
    noFavorites: 'No Favorites',
    noFavoritesDesc: 'You haven\'t favorited any articles yet',
    browseArticles: 'Browse Articles',
    confirmClearAll: 'Are you sure you want to clear all favorites?',
    // Archive translations
    archiveTitle: 'Article Archive',
    noArchivedArticles: 'No archived articles',
    totalArticles: 'Total Articles',
    timeRange: 'Time Range',
    // Password protection translations
    passwordProtected: 'Password Protected',
    enterPasswordToAccess: 'Enter password to access this website',
    password: 'Password',
    enterPassword: 'Enter access password',
    access: 'Access Website',
    checking: 'Verifying...',
    contactForAccess: 'Contact the site administrator for access',
    passwordRequired: 'Please enter password',
    incorrectPassword: 'Incorrect password',
    loginError: 'Error occurred during login, please try again later',
    passwordProtectionNotConfigured: 'Password protection not configured properly',
    // Footer translations
    footerDescription: 'A modern personal blog and technology sharing platform',
    allRightsReserved: 'All rights reserved',
    siteVisitors: 'Site Visitors',
    siteViews: 'Site Views',
    pageViews: 'Page Views',
    // Reading progress translations
    continueReading: 'Continue Reading',
    recentlyViewed: 'Recently',
    clearRecent: 'Clear',
    noRecentArticles: 'No recently viewed articles',
    // Document viewer translations
    loadingDocument: 'Loading document...',
    documentLoadError: 'Failed to load document',
    retry: 'Retry',
    documentPreviewNotAvailable: 'Document preview is not available',
    documentFormat: 'Format: {format}',
    downloadAndViewLocally: 'Download and view locally',
    document: 'Document',
    documentConversionNotSupported: 'Document format not supported for conversion preview',
    // PDF viewer translations
    prevPage: 'Previous Page (←)',
    nextPage: 'Next Page (→)',
    pageNumber: 'Page Number',
    jumpToPage: 'Jump to Page',
    jump: 'Go',
    zoomOut: 'Zoom Out (↓)',
    reset: 'Reset (0)',
    zoomIn: 'Zoom In (↑)',
    rotate: 'Rotate (R)',
    // Excel 查看器相关翻译
    file: 'File',
    insert: 'Insert',
    formula: 'Formula',
    openFile: 'Open File',
    pleaseWait: 'Please wait...',
    initializingExcelEngine: 'Initializing Excel engine...',
    loadingStyles: 'Loading styles...',
    loadingCoreEngine: 'Loading core engine...',
    resourceLoadFailed: 'Failed to load resources, please check network or refresh',
    newWorkbook: 'New Workbook',
    workbook1: 'Workbook1',
    parsingExcelFile: 'Parsing Excel file...',
    readFailed: 'Read failed',
    checkFileFormat: 'Please check file format',
    parseFailed: 'Parse failed',
    ensureValidXlsx: 'Please ensure it is a valid .xlsx file',
    loadingExcelFromUrl: 'Loading Excel from URL...',
    remoteFile: 'remote-file.xlsx',
    loadFailedCheckUrl: 'Failed to load, please check if URL is correct',
    excelEngineNotReady: 'Excel engine is not ready yet, please try again later',
    // 新增翻译项
    saveAs: 'Save As',
    fullscreen: 'Fullscreen',
    featureActivated: 'Feature activated, please use the toolbar above to operate',
    unableToFindContainer: 'Unable to find container element',
    fullscreenNotSupported: 'Fullscreen is not supported in current browser',
    noDataToSave: 'No data to save',
    enterFileName: 'Please enter file name',
    saveFailed: 'Failed to save',
    noDataToPrint: 'No data to print',
    printFailed: 'Failed to print',
    popupBlocked: 'Popup blocked, please allow popups and try again',
    printPreview: 'Print Preview',
    info: 'Info',
    cancel: 'Cancel',
    confirm: 'Confirm',
    editArticles: 'Edit Articles',
    edit: 'Edit',
    articleEditor: 'Article Editor',
    saving: 'Saving...',
    save: 'Save',
    files: 'Files',
    newFile: 'New File',
    newFolder: 'New Folder',
    editorPlaceholder: 'Enter article content here...',
    noFileSelected: 'No File Selected',
    noFileSelectedDesc: 'Please select a file to start editing, or create a new file',
    gitIntegration: 'Git Integration',
    enterGitToken: 'Please enter your Git access token to enable file editing functionality',
    gitProvider: 'Git Provider',
    accessToken: 'Access Token',
    enterAccessToken: 'Enter access token',
    failedToLoadFile: 'Failed to load file',
    confirmDelete: 'Confirm Delete',
    confirmDeleteFile: 'Are you sure you want to delete the file "{filename}"? This action cannot be undone.',
    fileDeleted: 'File deleted',
    failedToDeleteFile: 'Failed to delete file',
    fileCreated: 'File created',
    failedToCreateFile: 'Failed to create file',
    folderCreated: 'Folder created',
    failedToCreateFolder: 'Failed to create folder',
    renamed: 'Renamed',
    failedToRename: 'Failed to rename',
    pleaseEnterToken: 'Please enter access token',
    tokenSaved: 'Token saved',
    articleSaved: 'Article saved',
    failedToSaveArticle: 'Failed to save article',
    fileName: 'File name',
    folderName: 'Folder name',
    newName: 'New name',
    create: 'Create',
    rename: 'Rename',
    delete: 'Delete',
    dataManager:'Data Manager',
    noRepoInfo:'Repo not configured',
    chooseEditor:'Choose Editor',
    selectEditorToOpenRepo:'Please select an online editor to open the repository',
    top:'Sticky',
  }
}




